# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 271, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.listName.setObjectName("listName")
        self.verticalLayout.addWidget(self.listName)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.accTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.accTable.setObjectName("accTable")
        self.accTable.setColumnCount(1)
        self.accTable.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.accTable.setHorizontalHeaderItem(0, item)
        self.accTable.horizontalHeader().setVisible(False)
        self.accTable.horizontalHeader().setStretchLastSection(True)
        self.accTable.verticalHeader().setVisible(False)
        self.accTable.verticalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.accTable)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "List Name"))
        self.label_2.setText(_translate("Dialog", "Accounts"))
        item = self.accTable.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "Neue Zeile"))
        item = self.accTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Neue Spalte"))


